language: r
cache: packages

matrix:
  include:
  - r: devel
    os: linux
  - r: release
    os: linux
  - r: release
    os: osx

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - ropensci/spelling
  - MangoTheCat/goodpractice

before_install:
  # Lapack
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install liblapack-dev; fi
  # PDF
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr update --self; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install inconsolata; fi
  # libgit2-dev
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libgit2-dev; fi

before_script:
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo pip install proselint; fi
  # markdown-link-check, does not work temporarily
  #- sudo apt-get install npm
  #- sudo npm install -g markdown-link-check

after_success:
  # Lint
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then Rscript -e 'lintr::lint_package()'; fi
  # Codecov
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "devel" ]; then travis_wait 20 Rscript -e 'covr::codecov()'; fi
  # Proselint
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  # Goodpractice
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then travis_wait 60 Rscript -e 'goodpractice::gp()'; fi
  # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/check_no_local_files; fi
  - # Do a CRAN build
  - cd scripts; ./build_cran
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_failure:
  - Rscript -e 'print(rappdirs::app_dir()$os)'
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

